### ISSUE TITLE
AttributeError when trying to upload an image

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.upload#12]
this error was introduced in 6c26cea1c8c80742fbf26196f9cb2440143d6e76

``` python
Traceback (innermost last):
  Module ZPublisher.Publish, line 126, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 46, in call_object
  Module collective.upload.browser, line 70, in __call__
  Module collective.upload.browser, line 177, in getContextInfo
AttributeError: 'NoneType' object has no attribute 'url'
```
